# Generated by Django 3.0.6 on 2020-05-25 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='updateTime',
            new_name='updateDate',
        ),
    ]
